from typing import Any

class FieldView:
    def __len__(self) -> int: ...

class RawWorld:
    def __init__(self) -> None: ...
    def register_component(self, name: str, fields: list[tuple[str, str]]) -> None: ...
    def create_entity(self) -> int: ...
    def kill_entity(self, entity_id: int) -> None: ...
    def add_component(
        self, entity_id: int, component_name: str, values: dict[str, Any]
    ) -> None: ...
    def remove_component(self, entity_id: int, component_name: str) -> None: ...
    def has_component(self, entity_id: int, component_name: str) -> bool: ...
    def get_component(self, entity_id: int, component_name: str) -> dict[str, Any]: ...
    def get_component_field(self, entity_id: int, component_name: str, field_name: str) -> Any: ...
    def set_component_field(
        self,
        entity_id: int,
        component_name: str,
        field_name: str,
        value: Any,
    ) -> None: ...
    def query_entities(
        self, with_components: list[str], without_components: list[str]
    ) -> list[int]: ...
    def component_field_view(self, component_name: str, field_name: str) -> FieldView: ...
    def component_field_values(self, component_name: str, field_name: str) -> list[Any]: ...
    def alive_count(self) -> int: ...

__version__: str
